env = Environment()
env.Append(LIBS = ['pthread', 'cppunit'])

source = ['../request.cpp','../context.cpp']
source += Glob('*.cpp')

env.Program('test_suite', source ,CXXFLAGS='-Wall -pedantic -Os -g')
